name: Deploy Vlille Ingestion

on:
  push:
    branches: [main]
    paths: ['data-ingestion/vlille/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # On reste sur la version moderne que tu utilises
      - name: Install test dependencies
        run: |
          pip install pytest psycopg2-binary
      - name: Run tests
        # On teste uniquement la logique Python
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/data-ingestion/vlille
          pytest data-ingestion/vlille/tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Package Lambda function
        run: |
          # 1. On va dans le dossier source
          cd data-ingestion/vlille
          
          # 2. On crée le ZIP avec UNIQUEMENT ton code Python.
          # On n'installe PAS psycopg2 ici car on utilise la Layer AWS.
          zip -r ../../deployment.zip . -x "tests/*" -x "__pycache__/*" -x "*.pyc" -x "requirements*"
          
      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name fetch_vlille_data \
            --zip-file fileb://deployment.zip